export const PRODUCTOS = [
    {id: 1, title: "Cortina Roller Blackout", description: ["En The Roller House, nuestras cortinas blackout están diseñadas para bloquear hasta el 99% de la luz exterior, creando un ambiente oscuro y relajante ideal para dormir, ver películas o regular la temperatura en cualquier espacio","Ideal para: Dormitorios, home theaters, guarderías y espacios donde la privacidad y el confort son esenciales."]},
    {id: 2, title: "Cortina Roller Screen", description: ["Diseñadas para ofrecer control de luz y privacidad con un estilo minimalista. Disponibles en tejidos translúcidos, opacos o blackout, se adaptan a cualquier espacio.","Ideal para: Oficinas, hogares, vidrieras","Beneficios: Limpieza sencilla, protección solar, elegancia discreta (sin obstruir la vista exterior)"]},
    {id: 3, title: "Cortina Roller Dimout", description: ["Controla la luz natural con elegancia: filtra los rayos solares sin oscurecer completamente el ambiente. Tejido técnico que difumina la luminosidad, reduciendo el resplandor y protegiendo tus muebles de los rayos UV, manteniendo una atmósfera acogedora y con privacidad.","Ideal para: Salas de estar, cocinas, oficinas.", "Beneficios clave: Regula la temperatura, estética moderna, luz suave."]},
    {id: 4, title: "Cortina Roller Translúcida", description: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."]},
    {id: 5, title: "Cortina Roller Térmica", description: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."]},
    {id: 6, title: "Cortina Roller Motorizada", description: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."]},
    {id: 7, title: "Cortina Roller con Estampado", description: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."]},
    {id: 8, title: "Cortina Roller con Diseño Personalizado", description: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."]}, 
]